from __future__ import annotations

import sqlalchemy as sa

metadata = sa.MetaData()

workflow_definitions = sa.Table(
    "workflow_definitions",
    metadata,
    sa.Column("workflow_key", sa.String(length=128), nullable=False),
    sa.Column("version", sa.String(length=32), nullable=False),
    sa.Column("title", sa.String(length=255), nullable=False),
    sa.Column("description", sa.String(length=1024), nullable=False),
    sa.Column("target_type", sa.String(length=32), nullable=False),
    sa.Column("input_schema_json", sa.JSON(), nullable=False),
    sa.Column("ui_schema_json", sa.JSON(), nullable=True),
    sa.Column("mistral_workflow_name", sa.String(length=255), nullable=False),
    sa.Column("required_capability", sa.String(length=128), nullable=False),
    sa.Column("required_scope_type", sa.String(length=32), nullable=False),
    sa.Column("risk_level", sa.String(length=32), nullable=False),
    sa.Column("approval_mode", sa.String(length=32), nullable=False),
    sa.Column("cancel_policy", sa.String(length=32), nullable=False),
    sa.Column("enabled_environments_json", sa.JSON(), nullable=False),
    sa.Column("checksum", sa.String(length=128), nullable=False),
    sa.Column("enabled", sa.Boolean(), nullable=False),
    sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint("workflow_key", "version"),
    sa.Index(
        "ix_workflow_definitions_enabled",
        "enabled",
        "workflow_key",
        "version",
    ),
)

operations = sa.Table(
    "operations",
    metadata,
    sa.Column("operation_id", sa.String(length=128), nullable=False),
    sa.Column("workflow_key", sa.String(length=128), nullable=False),
    sa.Column("workflow_version", sa.String(length=32), nullable=False),
    sa.Column("definition_checksum", sa.String(length=128), nullable=False),
    sa.Column("actor_subject_id", sa.String(length=128), nullable=False),
    sa.Column("scope_type", sa.String(length=32), nullable=False),
    sa.Column("scope_id", sa.String(length=128), nullable=True),
    sa.Column("status", sa.String(length=32), nullable=False),
    sa.Column("request_hash", sa.String(length=128), nullable=False),
    sa.Column("idempotency_key_hash", sa.String(length=128), nullable=False),
    sa.Column("target_snapshot_json", sa.JSON(), nullable=False),
    sa.Column("input_json", sa.JSON(), nullable=False),
    sa.Column("correlation_id", sa.String(length=128), nullable=False),
    sa.Column("external_execution_id", sa.String(length=128), nullable=True),
    sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
    sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=False),
    sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
    sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint("operation_id"),
    sa.Index(
        "ix_operations_actor_status_created",
        "actor_subject_id",
        "status",
        "created_at",
        "operation_id",
    ),
    sa.Index("ix_operations_correlation", "correlation_id", unique=True),
    sa.Index("ix_operations_external_execution", "external_execution_id"),
)

operation_targets = sa.Table(
    "operation_targets",
    metadata,
    sa.Column("operation_id", sa.String(length=128), nullable=False),
    sa.Column("target_type", sa.String(length=32), nullable=False),
    sa.Column("cloud_id", sa.String(length=128), nullable=False),
    sa.Column("region_id", sa.String(length=128), nullable=False),
    sa.Column("resource_id", sa.String(length=128), nullable=False),
    sa.Column("snapshot_json", sa.JSON(), nullable=False),
    sa.Column("status", sa.String(length=32), nullable=False),
    sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint("operation_id", "target_type", "cloud_id", "region_id", "resource_id"),
    sa.ForeignKeyConstraint(["operation_id"], ["operations.operation_id"], ondelete="CASCADE"),
)

operation_events = sa.Table(
    "operation_events",
    metadata,
    sa.Column("event_id", sa.String(length=128), nullable=False),
    sa.Column("operation_id", sa.String(length=128), nullable=False),
    sa.Column("event_type", sa.String(length=64), nullable=False),
    sa.Column("from_status", sa.String(length=32), nullable=True),
    sa.Column("to_status", sa.String(length=32), nullable=True),
    sa.Column("outcome", sa.String(length=32), nullable=False),
    sa.Column("safe_message", sa.String(length=1024), nullable=False),
    sa.Column("safe_error_code", sa.String(length=128), nullable=True),
    sa.Column("metadata_json", sa.JSON(), nullable=False),
    sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint("event_id"),
    sa.ForeignKeyConstraint(["operation_id"], ["operations.operation_id"], ondelete="CASCADE"),
    sa.Index(
        "ix_operation_events_operation_created",
        "operation_id",
        "created_at",
        "event_id",
    ),
)

operation_attempts = sa.Table(
    "operation_attempts",
    metadata,
    sa.Column("attempt_id", sa.String(length=128), nullable=False),
    sa.Column("operation_id", sa.String(length=128), nullable=False),
    sa.Column("attempt_number", sa.Integer(), nullable=False),
    sa.Column("adapter_action", sa.String(length=64), nullable=False),
    sa.Column("outcome", sa.String(length=32), nullable=False),
    sa.Column("external_execution_id", sa.String(length=128), nullable=True),
    sa.Column("safe_error_code", sa.String(length=128), nullable=True),
    sa.Column("metadata_json", sa.JSON(), nullable=False),
    sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint("attempt_id"),
    sa.ForeignKeyConstraint(["operation_id"], ["operations.operation_id"], ondelete="CASCADE"),
    sa.Index(
        "ix_operation_attempts_operation_created",
        "operation_id",
        "created_at",
        "attempt_id",
    ),
)

operation_outbox = sa.Table(
    "operation_outbox",
    metadata,
    sa.Column("outbox_id", sa.String(length=128), nullable=False),
    sa.Column("operation_id", sa.String(length=128), nullable=False),
    sa.Column("event_type", sa.String(length=64), nullable=False),
    sa.Column("state", sa.String(length=32), nullable=False),
    sa.Column("attempt_count", sa.Integer(), nullable=False),
    sa.Column("not_before_at", sa.DateTime(timezone=True), nullable=False),
    sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint("outbox_id"),
    sa.ForeignKeyConstraint(["operation_id"], ["operations.operation_id"], ondelete="CASCADE"),
    sa.Index("ix_operation_outbox_state_created", "state", "created_at", "outbox_id"),
)

operation_idempotency_keys = sa.Table(
    "operation_idempotency_keys",
    metadata,
    sa.Column("actor_subject_id", sa.String(length=128), nullable=False),
    sa.Column("workflow_key", sa.String(length=128), nullable=False),
    sa.Column("workflow_version", sa.String(length=32), nullable=False),
    sa.Column("scope_hash", sa.String(length=128), nullable=False),
    sa.Column("key_hash", sa.String(length=128), nullable=False),
    sa.Column("request_hash", sa.String(length=128), nullable=False),
    sa.Column("operation_id", sa.String(length=128), nullable=False),
    sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint(
        "actor_subject_id",
        "workflow_key",
        "workflow_version",
        "scope_hash",
        "key_hash",
    ),
    sa.ForeignKeyConstraint(["operation_id"], ["operations.operation_id"], ondelete="CASCADE"),
    sa.Index("ix_operation_idempotency_created", "created_at", "operation_id"),
)
